language: rust
dist: focal
rust:
- nightly
cache:
  cargo: true
install:
- rustup update
- rustup component add clippy rustfmt --toolchain nightly
- cargo install grcov rust-covfix
jobs:
  include:
  - stage: unit tests
    script:
    - cargo test
  - stage: check rustfmt style && run clippy
    script:
    - cargo clippy -Z unstable-options -- -D warnings
    - cargo fmt --all -- --check
  - stage: coverage sending
    script:
    - bash coverage.sh ontravis sendcov
env:
  global:
    secure: PNxMVZn11lg7UKNcQuOSRFtJp8sclsVYE2O4LPZOwvA6U+rLnk7bLqkZjhjW2Knl+a0MI4mm/F/1EyOu7cxcSfnBvvn9PaeoTDodmi+UDw8oPdBA3LIH9U+sbzovvsLF1+HTgnxQzJfXgJQuJ+NyqMIYZ2Z+53I9P68P0F2Xzf9FZdsD+UjIdK7wtRHVcvsGi4Qyvin8jQ+lqw9vd5HIdMp2Ebv6pvAS5n5F3o2pEGuriH9dUc1Y2nCeD1R5FrXFVtxmTM92D3aY8UbKcX4UpyJo7xDc1+dDdZVkU7diYyXndIwfiZMUNdsAYFJ/PzipXNcDiV7Yw9logXFS+rjGDcKLt+RnSAqXLo084VCEi6SFgl5PLXg+44ggseRhkPdGt9+3XxIG2rzdVFXQiReCBu7Z+PY3aKhLQRzE6zN6tsZdVi9DOOTnjM1Ax30zwJqvPHGY7v4Zsrsx7KTR/GHDgGrVGSDucNHXwUL30/rgojyg8E0tO51RSCWB0V1RjV8kzFjRGmVAaLFZgO2bC3U/Nqskfn8hdE+lE/AMiGe2ZCeG2MPkwn/HaM99IMJLPMaQPW+makClAPNzA4nzhXxT9txu/JYLZcLjEeh6tkYW9OlMDwLT4mGfQXdoqJ6iSWfZL5okFkPuqZ2rkJI34VXKt9W4zs7XVZ8B3PderMnOLtA=
